CREATE TABLE IF NOT EXISTS estamelecimentos (
    cnpj char(8) NOT NULL,
    cnpj_ordem char(4) NOT NULL,
    cnpj_digito_verificador char(2) NOT NULL,
    identificador_matriz_filial integer NULL,
    nome_fantasia text NULL,
    situacao_cadastral integer NULL,
    data_situacao_cadastral date NULL,
    motivo_situacao_cadastral integer NULL,
    nome_cidade_exterior text NULL,
    pais test NULL,
    data_inicio_atividade date NULL,
    cnae_principal integer NULL,
    cnaes_secundaria text NULL,
    tipo_logradouro text NULL,
    logradouro text NULL,
    numero text NULL,
    complemento text NULL,
    bairro text NULL,
    cep text NULL,
    uf text NULL,
    municipio integer NULL,
    ddd1 text NULL,
    telefone1 text NULL,
    ddd2 text NULL,
    telefone2 text NULL,
    ddd_fax text NULL,
    fax text NULL,
    email text NULL,
    situacao_especial text NULL,
    data_situacao_especial text NULL
);

CREATE INDEX IF NOT EXISTS idx_estabelecimento_cnpj ON estabelecimentos USING btree (cnpj, cnpj_ordem, cnpj_dv);
