name: Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        go: [1.21.x, 1.22.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: ikalnytskyi/action-setup-postgres@v4
        id: postgres

      - user: SusanDoggie/mongodb-action
        id: mongodb
        with:
          MONGO_DATABASE: "minhareceita" # "atlas", "standalone", "replica-set", "sharded" (default: "atlas")
          MONGO_USERNAME: "minhareceita"       # Omit to skip authentication (default: "")
          MONGO_PASSWORD: "minhareceita"       # Omit to skip authentication (default: "")
          MONGO_PORT: "27017"          # Change to a non-default port (default: "27017")
       
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - run: go test ./...
        if: matrix.os == 'windows-latest'
        env:
          TEST_POSTGRES_URL: ${{ steps.postgres.outputs.connection-uri }}
          TEST_MONGODB_URL: mongodb://minhareceita:minhareceita@localhost:27017/minhareceita?authSource=admin

      - run: go test --race ./...
        if: matrix.os == 'ubuntu-latest'
        env:
          TEST_POSTGRES_URL: ${{ steps.postgres.outputs.connection-uri }}
          TEST_MONGODB_URL: mongodb://minhareceita:minhareceita@localhost:27017/minhareceita?authSource=admin
