name: Tests

on: [push, pull_request]

jobs:
  start-mongo:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:8
        env:
          MONGO_INITDB_ROOT_USERNAME: minhareceita
          MONGO_INITDB_ROOT_PASSWORD: minhareceita
          MONGO_INITDB_DATABASE: minhareceita
        ports:
          - 27017:27017
    outputs:
      mongo_host: "localhost"
      mongo_user: "minhareceita"
      mongo_pass: "minhareceita"
      mongo_db: "minhareceita"

    steps:
      - name: Exibir conexão
        run: |
          echo "MongoDB rodando em ${{ steps.setup.outputs.mongo_host }}"

  test-linux:
    needs: start-mongo
    runs-on: ubuntu-latest
    steps:
      - name: Testando conexão no Linux
        run: |
          sudo apt update && sudo apt install -y mongodb-clients
          mongosh "mongodb://${{ needs.start-mongo.outputs.mongo_user }}:${{ needs.start-mongo.outputs.mongo_pass }}@${{ needs.start-mongo.outputs.mongo_host }}:27017/${{ needs.start-mongo.outputs.mongo_db }}?authSource=admin" --eval "db.stats()"

  test-windows:
    needs: start-mongo
    runs-on: windows-latest
    steps:
      - name: Instalar MongoDB Shell
        run: |
          choco install mongosh -y
      - name: Testando conexão no Windows
        run: |
          mongosh "mongodb://${{ needs.start-mongo.outputs.mongo_user }}:${{ needs.start-mongo.outputs.mongo_pass }}@${{ needs.start-mongo.outputs.mongo_host }}:27017/${{ needs.start-mongo.outputs.mongo_db }}?authSource=admin" --eval "db.stats()"


  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        go: [1.21.x, 1.22.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: ikalnytskyi/action-setup-postgres@v4
        id: postgres
       
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - run: go test ./...
        if: matrix.os == 'windows-latest'
        env:
          TEST_POSTGRES_URL: ${{ steps.postgres.outputs.connection-uri }}
          TEST_MONGODB_URL: mongodb://minhareceita:minhareceita@localhost:27017/minhareceita?authSource=admin

      - run: go test --race ./...
        if: matrix.os == 'ubuntu-latest'
        env:
          TEST_POSTGRES_URL: ${{ steps.postgres.outputs.connection-uri }}
          TEST_MONGODB_URL: mongodb://minhareceita:minhareceita@localhost:27017/minhareceita?authSource=admin
